- type: 'status'
  details:
    # When using YAML checks storage, we must provide identifier to link each
    # check with its result.  This is important for only notifying when the
    # state *changes* -- we must store a limited amount of historical data to
    # do this (and also do clever stuff like detect 'flapping' etc. 
    identifier: 'google-status-check'
    path: 'https://www.google.co.uk/you-suck-balls'
    responders:
      - hipchat
- type: 'status'
  details:
    identifier: 'tomrussell-status-check'
    path: 'http://www.tomrussell.co.uk/'
    responders:
      - hipchat
